/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedMessagesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEncryptedMessage"
      | "getEncryptedTimestamp"
      | "getMessageCount"
      | "getMessageMetadata"
      | "getUserMessages"
      | "messageExists"
      | "protocolId"
      | "submitMessage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MessageDecrypted" | "MessageSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getEncryptedMessage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTimestamp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMessages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMessage",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitMessage",
    data: BytesLike
  ): Result;
}

export namespace MessageDecryptedEvent {
  export type InputTuple = [sender: AddressLike, messageId: BigNumberish];
  export type OutputTuple = [sender: string, messageId: bigint];
  export interface OutputObject {
    sender: string;
    messageId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSubmittedEvent {
  export type InputTuple = [
    sender: AddressLike,
    messageId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    messageId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    sender: string;
    messageId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedMessages extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedMessages;
  waitForDeployment(): Promise<this>;

  interface: EncryptedMessagesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEncryptedMessage: TypedContractMethod<
    [messageId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedTimestamp: TypedContractMethod<
    [messageId: BigNumberish],
    [string],
    "view"
  >;

  getMessageCount: TypedContractMethod<[], [bigint], "view">;

  getMessageMetadata: TypedContractMethod<
    [messageId: BigNumberish],
    [
      [string, bigint, boolean] & {
        sender: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getUserMessages: TypedContractMethod<[], [bigint[]], "view">;

  messageExists: TypedContractMethod<
    [messageId: BigNumberish],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitMessage: TypedContractMethod<
    [
      encryptedContent: BytesLike,
      encryptedTimestamp: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEncryptedMessage"
  ): TypedContractMethod<[messageId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTimestamp"
  ): TypedContractMethod<[messageId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMessageCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMessageMetadata"
  ): TypedContractMethod<
    [messageId: BigNumberish],
    [
      [string, bigint, boolean] & {
        sender: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserMessages"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "messageExists"
  ): TypedContractMethod<[messageId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitMessage"
  ): TypedContractMethod<
    [
      encryptedContent: BytesLike,
      encryptedTimestamp: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "MessageDecrypted"
  ): TypedContractEvent<
    MessageDecryptedEvent.InputTuple,
    MessageDecryptedEvent.OutputTuple,
    MessageDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSubmitted"
  ): TypedContractEvent<
    MessageSubmittedEvent.InputTuple,
    MessageSubmittedEvent.OutputTuple,
    MessageSubmittedEvent.OutputObject
  >;

  filters: {
    "MessageDecrypted(address,uint256)": TypedContractEvent<
      MessageDecryptedEvent.InputTuple,
      MessageDecryptedEvent.OutputTuple,
      MessageDecryptedEvent.OutputObject
    >;
    MessageDecrypted: TypedContractEvent<
      MessageDecryptedEvent.InputTuple,
      MessageDecryptedEvent.OutputTuple,
      MessageDecryptedEvent.OutputObject
    >;

    "MessageSubmitted(address,uint256,uint256)": TypedContractEvent<
      MessageSubmittedEvent.InputTuple,
      MessageSubmittedEvent.OutputTuple,
      MessageSubmittedEvent.OutputObject
    >;
    MessageSubmitted: TypedContractEvent<
      MessageSubmittedEvent.InputTuple,
      MessageSubmittedEvent.OutputTuple,
      MessageSubmittedEvent.OutputObject
    >;
  };
}
